//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koloskov_MasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
            this.SupplyHistory = new HashSet<SupplyHistory>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Surname { get; set; }
        public string Patronimyc { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public System.DateTime PassportIssueDate { get; set; }
        public string PassportIssuerName { get; set; }
        public string PassportDepartmentCode { get; set; }
        public string BankAccountNumber { get; set; }
        public string CorrespondentAccountNumber { get; set; }
        public long BankIdentificationCode { get; set; }
        public string BankName { get; set; }
        public bool FamilyCheck { get; set; }
        public string HealthCondition { get; set; }
        public int EmployeeRole { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyHistory> SupplyHistory { get; set; }
    }
}
