//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koloskov_MasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int OrderID { get; set; }
        public int Partner { get; set; }
        public string ProductArticle { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
